name: bad_fl
description: "A flutter package, including components, implementations, helper functions and extensions. Designed to provide a simple way to develop with flutter."
version: 0.7.2
# publish_to: https://pub.dev # this will cause error when publish ...
homepage: https://github.com/badlopo/bad_fl
repository: https://github.com/badlopo/bad_fl

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  device_info_plus: ^10.1.0  # https://pub.dev/packages/device_info_plus/changelog#1001
  dio: ^5.4.2+1
  easy_refresh: ^3.4.0
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.2
  hive_ce: ^2.8.0
  hive_ce_flutter: ^2.1.0
  image_gallery_saver_plus: ^3.0.5
  image_picker: ^1.1.0
  package_info_plus: ^8.0.0  # https://pub.dev/packages/package_info_plus/changelog#600
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
